services:
  postgres:
    image: postgres:16-alpine
    container_name: tv360_postgres
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bss-network

  backend:
    build:
      context: ./backend/backend-bss
      dockerfile: Dockerfile
    container_name: tv360_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - bss-network

  frontend:
    build:
      context: ./frontend/frontend-bss
      dockerfile: Dockerfile
    container_name: tv360_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - bss-network

  label-studio:
    image: heartexlabs/label-studio:1.13.1
    platform: linux/amd64
    container_name: tv360_label_studio
    ports:
      - "8081:8080"
    volumes:
      - label-studio-data:/label-studio/data
    environment:
      - LABEL_STUDIO_HOST=${LS_HOST}
      - CSRF_TRUSTED_ORIGINS=https://annalise-prehostile-infrequently.ngrok-free.dev,http://localhost:8081
      - LABEL_STUDIO_DB_DIALECT=sqlite
    restart: unless-stopped
    networks:
      - bss-network

volumes:
  postgres_data:
  label-studio-data:

networks:
  bss-network:
    external: true