# Local development - connects to Docker postgres on localhost
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:bss-db-schema}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:123456aA@}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=9a437fddbafd3b9c83d757264ba2bcbd1c27ff58223bfedffd513837ce404f35
jwt.expiration=86400000