services:
  n8n:
    build: .
    container_name: tv360_n8n
    restart: always
    environment:
      GENERIC_TIMEZONE: Asia/Ho_Chi_Minh
      TZ: Asia/Ho_Chi_Minh
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
    volumes:
      - ./n8n_data:/home/node/.n8n
    ports:
      - "5679:5678"
    networks:
      - bss-network

networks:
  bss-network:
    external: true