import { useState, useEffect, useMemo } from 'react';
import { useSearchParams } from 'react-router-dom';
import {
    ChevronRight, Download, Calendar, FileSpreadsheet,
    Clock, CheckCircle2, AlertTriangle, Loader2
} from 'lucide-react';
import EditorLayout from '../components/EditorLayout';
import axiosClient from '../api/axiosClient';

/**
 * Tools > Export XLSX
 *
 * Lets an editor pick channels + a date range + which data to include, then
 * downloads an .xlsx generated by the backend (GET /api/editor/export/xlsx).
 * The browser saves the file directly using the server-suggested name.
 *
 * Can be opened pre-filled from a channel's page:
 *   /editor/export?channelId=VTV1&date=2026-05-24
 * which selects only that channel and sets the date range to that single day.
 *
 * "Recent Exports" is tracked per-browser in localStorage — there is no
 * server-side export history, so we record what this editor downloaded here.
 */

const RECENTS_KEY = 'bss.recentExports';
const MAX_RECENTS = 6;

const DATA_TYPES = [
    {
        key: 'includePrograms',
        label: 'Published Schedule',
        hint: 'The live, approved programs (default).',
        default: true,
    },
    {
        key: 'includeDrafts',
        label: 'Draft Programs',
        hint: 'Programs still pending AI / editor review.',
        default: false,
    },
    {
        key: 'includeLogs',
        label: 'Reschedule Logs',
        hint: 'Added / modified / deleted change history.',
        default: false,
    },
];

function humanSize(bytes) {
    if (bytes == null) return '';
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function nowLabel() {
    return new Date().toLocaleString(undefined, {
        year: 'numeric', month: 'short', day: 'numeric',
        hour: '2-digit', minute: '2-digit',
    });
}

/** Pull the file name out of a Content-Disposition header, falling back gracefully. */
function filenameFromDisposition(disposition, fallback) {
    if (!disposition) return fallback;
    // filename*=UTF-8''My%20File.xlsx  (preferred — handles non-ASCII)
    const star = /filename\*=UTF-8''([^;]+)/i.exec(disposition);
    if (star?.[1]) {
        try { return decodeURIComponent(star[1]); } catch { /* fall through */ }
    }
    const plain = /filename="?([^";]+)"?/i.exec(disposition);
    return plain?.[1] || fallback;
}

function loadRecents() {
    try {
        const raw = localStorage.getItem(RECENTS_KEY);
        return raw ? JSON.parse(raw) : [];
    } catch {
        return [];
    }
}

export default function ExportXLSX() {
    const [searchParams] = useSearchParams();
    const prefillChannel = searchParams.get('channelId');
    const prefillDate = searchParams.get('date'); // ISO yyyy-MM-dd

    // Data
    const [channels, setChannels] = useState([]);
    const [channelsLoading, setChannelsLoading] = useState(true);
    const [channelsError, setChannelsError] = useState(null);

    // Form State — seed the date range from the pre-fill (single day) if present.
    const [dateRange, setDateRange] = useState({
        start: prefillDate || '',
        end: prefillDate || '',
    });
    const [selectedChannels, setSelectedChannels] = useState([]); // channel IDs
    const [includeData, setIncludeData] = useState(
        Object.fromEntries(DATA_TYPES.map(d => [d.key, d.default]))
    );

    // Export Process State
    const [isExporting, setIsExporting] = useState(false);
    const [exportError, setExportError] = useState(null);
    const [lastExport, setLastExport] = useState(null); // { filename, size }
    const [showSuccessModal, setShowSuccessModal] = useState(false);
    const [recentExports, setRecentExports] = useState(loadRecents);

    // --- Load channels once ---
    useEffect(() => {
        let active = true;
        (async () => {
            try {
                // size=1000 → grab them all; the channel table is small.
                const { data } = await axiosClient.get('/api/editor/channels', {
                    params: { size: 1000, sort: 'id,asc' },
                });
                if (!active) return;
                const list = (data?.content ?? data ?? []).map(c => ({
                    id: c.id,
                    name: c.name,
                    exportIds: c.exportIds ?? [],
                }));
                setChannels(list);
                // Pre-fill: select only the requested channel if it exists; else all.
                if (prefillChannel && list.some(c => c.id === prefillChannel)) {
                    setSelectedChannels([prefillChannel]);
                } else {
                    setSelectedChannels(list.map(c => c.id));
                }
            } catch {
                if (active) setChannelsError('Could not load channels. Please try again.');
            } finally {
                if (active) setChannelsLoading(false);
            }
        })();
        return () => { active = false; };
    }, [prefillChannel]);

    // --- Derived ---
    const allSelected = channels.length > 0 && selectedChannels.length === channels.length;
    const anyDataType = useMemo(
        () => Object.values(includeData).some(Boolean),
        [includeData]
    );
    const canExport = !isExporting && selectedChannels.length > 0 && anyDataType && !channelsLoading;

    // --- Handlers ---
    const toggleChannel = (id) => {
        setSelectedChannels(prev =>
            prev.includes(id) ? prev.filter(c => c !== id) : [...prev, id]
        );
    };

    const toggleAllChannels = () => {
        setSelectedChannels(allSelected ? [] : channels.map(c => c.id));
    };

    const toggleDataType = (key) => {
        setIncludeData(prev => ({ ...prev, [key]: !prev[key] }));
    };

    const recordRecent = (entry) => {
        setRecentExports(prev => {
            const next = [entry, ...prev].slice(0, MAX_RECENTS);
            try { localStorage.setItem(RECENTS_KEY, JSON.stringify(next)); } catch { /* ignore */ }
            return next;
        });
    };

    const handleExport = async (e) => {
        e.preventDefault();
        if (!canExport) return;

        setIsExporting(true);
        setExportError(null);

        // Build query params. channelIds is repeated (channelIds=A&channelIds=B)
        // so Spring binds it to List<String>.
        const params = new URLSearchParams();
        selectedChannels.forEach(id => params.append('channelIds', id));
        if (dateRange.start) params.append('dateFrom', dateRange.start);
        if (dateRange.end) params.append('dateTo', dateRange.end);
        DATA_TYPES.forEach(d => params.append(d.key, String(!!includeData[d.key])));

        try {
            const response = await axiosClient.get(
                `/api/editor/export/xlsx?${params.toString()}`,
                { responseType: 'blob' }
            );

            const filename = filenameFromDisposition(
                response.headers['content-disposition'],
                'BSS_Schedule.xlsx'
            );
            const blob = response.data;

            // Trigger the browser download.
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            a.remove();
            window.URL.revokeObjectURL(url);

            const entry = { filename, size: humanSize(blob.size), date: nowLabel() };
            setLastExport(entry);
            recordRecent(entry);
            setShowSuccessModal(true);
        } catch (err) {
            // Blob error bodies need decoding to read the message.
            let message = 'Export failed. Please try again.';
            try {
                if (err.response?.data instanceof Blob) {
                    const text = await err.response.data.text();
                    const parsed = JSON.parse(text);
                    message = parsed.message || message;
                }
            } catch { /* keep default */ }
            setExportError(message);
        } finally {
            setIsExporting(false);
        }
    };

    const breadcrumb = (
        <>
            <span>Tools</span>
            <ChevronRight className="w-4 h-4 mx-2" />
            <span className="text-[#2C3325] font-bold">Export XLSX</span>
        </>
    );

    return (
        <EditorLayout activeItem="export-xlsx" breadcrumb={breadcrumb}>
            <div className="p-4 sm:p-6 lg:p-8">

                <div className="mb-6">
                    <h1 className="text-2xl font-bold text-[#2C3325] flex items-center gap-2">
                        <FileSpreadsheet className="w-6 h-6 text-[#94A973]" />
                        Export Schedule Data
                    </h1>
                    <p className="text-sm text-[#6C755E] mt-1">Generate Excel reports of broadcast schedules, draft programs, and reschedule logs.</p>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

                    {/* LEFT: Export Configuration Form */}
                    <div className="lg:col-span-2">
                        <form onSubmit={handleExport} className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                            <div className="p-5 border-b border-gray-100 bg-[#FAFAFA]">
                                <h3 className="font-bold text-[#2C3325]">Export Configuration</h3>
                            </div>

                            <div className="p-6 space-y-8">

                                {/* Date Range */}
                                <div>
                                    <h4 className="text-sm font-bold text-[#6C755E] uppercase tracking-wide mb-3 flex items-center gap-2">
                                        <Calendar className="w-4 h-4" /> Date Range <span className="normal-case font-normal text-gray-400">(optional)</span>
                                    </h4>
                                    <div className="flex flex-col sm:flex-row gap-4">
                                        <div className="flex-1">
                                            <label className="block text-sm text-gray-600 mb-1">Start Date</label>
                                            <input
                                                type="date" value={dateRange.start}
                                                max={dateRange.end || undefined}
                                                onChange={e => setDateRange({ ...dateRange, start: e.target.value })}
                                                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#94A973] outline-none text-[#2C3325]"
                                            />
                                        </div>
                                        <div className="flex-1">
                                            <label className="block text-sm text-gray-600 mb-1">End Date</label>
                                            <input
                                                type="date" value={dateRange.end}
                                                min={dateRange.start || undefined}
                                                onChange={e => setDateRange({ ...dateRange, end: e.target.value })}
                                                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#94A973] outline-none text-[#2C3325]"
                                            />
                                        </div>
                                    </div>
                                    <p className="text-xs text-gray-400 mt-2">Leave empty to export the entire history.</p>
                                </div>

                                {/* Channel Selection */}
                                <div>
                                    <div className="flex justify-between items-end mb-3">
                                        <h4 className="text-sm font-bold text-[#6C755E] uppercase tracking-wide">
                                            Select Channels
                                            {!channelsLoading && (
                                                <span className="ml-2 normal-case font-normal text-gray-400">
                                                    {selectedChannels.length} / {channels.length}
                                                </span>
                                            )}
                                        </h4>
                                        {channels.length > 0 && (
                                            <button
                                                type="button" onClick={toggleAllChannels}
                                                className="text-xs font-semibold text-[#94A973] hover:text-[#4A533E] transition-colors"
                                            >
                                                {allSelected ? 'Deselect All' : 'Select All'}
                                            </button>
                                        )}
                                    </div>

                                    {channelsLoading ? (
                                        <div className="flex items-center gap-2 text-sm text-gray-500 py-6">
                                            <Loader2 className="w-4 h-4 animate-spin" /> Loading channels…
                                        </div>
                                    ) : channelsError ? (
                                        <div className="flex items-center gap-2 text-sm text-[#D54A4A] py-4">
                                            <AlertTriangle className="w-4 h-4" /> {channelsError}
                                        </div>
                                    ) : channels.length === 0 ? (
                                        <p className="text-sm text-gray-500 py-4">No channels available.</p>
                                    ) : (
                                        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 max-h-64 overflow-y-auto pr-1">
                                            {channels.map(channel => {
                                                const checked = selectedChannels.includes(channel.id);
                                                return (
                                                    <label key={channel.id} title={channel.id}
                                                        className={`flex items-start gap-2 p-3 rounded-lg border cursor-pointer transition-colors ${checked ? 'border-[#94A973] bg-[#F4F5F0]' : 'border-gray-200 hover:bg-gray-50'}`}>
                                                        <input
                                                            type="checkbox"
                                                            checked={checked}
                                                            onChange={() => toggleChannel(channel.id)}
                                                            className="w-4 h-4 mt-0.5 text-[#94A973] border-gray-300 rounded focus:ring-[#94A973] accent-[#94A973]"
                                                        />
                                                        <span className="min-w-0">
                                                            <span className="block text-sm font-medium text-[#2C3325] truncate">{channel.name || channel.id}</span>
                                                            {channel.exportIds?.length > 0 && (
                                                                <span className="mt-1 flex flex-wrap gap-1">
                                                                    {channel.exportIds.map(ex => (
                                                                        <span key={ex.type}
                                                                            className="inline-flex items-center gap-1 px-1.5 py-0.5 bg-white border border-[#E4E3CE] rounded text-[10px]">
                                                                            <span className="font-bold text-[#4A533E]">{ex.type}</span>
                                                                            <span className="font-mono text-gray-500">{ex.externalId}</span>
                                                                        </span>
                                                                    ))}
                                                                </span>
                                                            )}
                                                        </span>
                                                    </label>
                                                );
                                            })}
                                        </div>
                                    )}
                                </div>

                                {/* Data Types */}
                                <div>
                                    <h4 className="text-sm font-bold text-[#6C755E] uppercase tracking-wide mb-3">Include Data</h4>
                                    <div className="space-y-3">
                                        {DATA_TYPES.map(d => (
                                            <label key={d.key} className="flex items-start gap-3 cursor-pointer group">
                                                <input
                                                    type="checkbox" checked={!!includeData[d.key]}
                                                    onChange={() => toggleDataType(d.key)}
                                                    className="w-4 h-4 mt-0.5 text-[#94A973] border-gray-300 rounded focus:ring-[#94A973] accent-[#94A973]"
                                                />
                                                <span>
                                                    <span className="text-sm font-medium text-[#2C3325] group-hover:text-[#94A973] transition-colors">{d.label}</span>
                                                    <span className="block text-xs text-gray-400">{d.hint}</span>
                                                </span>
                                            </label>
                                        ))}
                                    </div>
                                    {!anyDataType && (
                                        <p className="text-xs text-[#D54A4A] mt-2">Select at least one data type.</p>
                                    )}
                                </div>

                            </div>

                            <div className="p-5 border-t border-gray-100 bg-[#FAFAFA] flex items-center justify-between gap-4">
                                {exportError ? (
                                    <span className="flex items-center gap-2 text-sm text-[#D54A4A]">
                                        <AlertTriangle className="w-4 h-4" /> {exportError}
                                    </span>
                                ) : <span />}
                                <button
                                    type="submit"
                                    disabled={!canExport}
                                    className="flex items-center gap-2 px-6 py-2.5 bg-[#94A973] hover:bg-[#8A9F6B] disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold rounded-lg transition-colors shadow-sm shrink-0"
                                >
                                    {isExporting ? (
                                        <>
                                            <Loader2 className="w-5 h-5 animate-spin" />
                                            Generating…
                                        </>
                                    ) : (
                                        <>
                                            <Download className="w-5 h-5" />
                                            Generate &amp; Download
                                        </>
                                    )}
                                </button>
                            </div>
                        </form>
                    </div>

                    {/* RIGHT: Recent Exports */}
                    <div className="lg:col-span-1">
                        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden h-full">
                            <div className="p-5 border-b border-gray-100 bg-[#FAFAFA]">
                                <h3 className="font-bold text-[#2C3325]">Recent Exports</h3>
                            </div>
                            <div className="p-4 space-y-3">
                                {recentExports.length === 0 ? (
                                    <p className="text-sm text-gray-400 text-center py-8">
                                        Your downloaded files will appear here.
                                    </p>
                                ) : (
                                    recentExports.map((file, i) => (
                                        <div key={i} className="p-3 border border-gray-100 rounded-lg hover:border-[#E4E3CE] hover:bg-[#FAFAFA] transition-colors">
                                            <div className="flex items-start gap-3 overflow-hidden">
                                                <div className="p-2 bg-[#F4F5F0] rounded-md text-[#94A973] shrink-0">
                                                    <FileSpreadsheet className="w-5 h-5" />
                                                </div>
                                                <div className="min-w-0">
                                                    <p className="text-sm font-bold text-[#2C3325] truncate" title={file.filename}>
                                                        {file.filename}
                                                    </p>
                                                    <div className="flex items-center gap-2 mt-1 text-xs text-gray-500">
                                                        <Clock className="w-3 h-3" /> {file.date}
                                                    </div>
                                                    <p className="text-xs text-gray-400 mt-0.5">{file.size}</p>
                                                </div>
                                            </div>
                                        </div>
                                    ))
                                )}
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            {/* SUCCESS MODAL */}
            {showSuccessModal && (
                <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
                    <div className="bg-white rounded-xl shadow-xl w-full max-w-sm overflow-hidden">
                        <div className="p-6 text-center">
                            <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-4">
                                <CheckCircle2 className="w-8 h-8 text-emerald-600" />
                            </div>
                            <h3 className="text-xl font-bold text-[#2C3325] mb-2">Export Complete!</h3>
                            <p className="text-sm text-[#6C755E] mb-6">
                                Your schedule data has been downloaded as an Excel spreadsheet.
                            </p>

                            <div className="bg-[#FAFAFA] p-3 rounded-lg border border-gray-100 mb-6 flex items-center gap-3 text-left">
                                <FileSpreadsheet className="w-5 h-5 text-[#94A973] shrink-0" />
                                <div className="min-w-0">
                                    <p className="text-sm font-bold text-[#2C3325] truncate" title={lastExport?.filename}>
                                        {lastExport?.filename}
                                    </p>
                                    <p className="text-xs text-gray-500">Just now • {lastExport?.size}</p>
                                </div>
                            </div>

                            <button
                                onClick={() => setShowSuccessModal(false)}
                                className="w-full px-4 py-2.5 bg-[#94A973] hover:bg-[#8A9F6B] text-white font-bold rounded-lg transition-colors shadow-sm"
                            >
                                Done
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </EditorLayout>
    );
}








